[package]
name = "stakedex-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "stakedex"
path = "src/main.rs"

[dependencies]
clap = { version = "^4.0", features = ["derive"] }
# required for solana-clap-utils
clap2 = { package = "clap", version = "^2.0" }
derive_more = "^0.99"
solana-clap-utils = "^1.9"
solana-cli-config = "^1.9"
solana-client = "^1.9"
solana-sdk = "^1.9"
spl-token = "^3.0"
stakedex_interface = { git = "https://github.com/igneous-labs/stakedex-sdk", branch = "master" }
