/**
 * Record the jsons generated by makeJsons on-chain
 */

const fs = require("fs");
const cp = require("child_process");

const MAX_DEXES_PER_CMD = 6;
const DEST_DIR = `${__dirname}/jsons`;
const CLI_EXEC = `${__dirname}/../../target/debug/stakedex`;

const FILES = fs.readdirSync(DEST_DIR);
const FNAME_REGEX = /^([a-zA-Z]+)([0-9]+).json$/;
FILES.sort((a, b) => {
  const [_aStr, aTy, aI] = a.match(FNAME_REGEX);
  const [_bStr, bTy, bI] = b.match(FNAME_REGEX);
  if (aTy !== bTy) {
    return aTy.localeCompare(bTy);
  }
  return Number(aI) - Number(bI);
});

for (let i = 0; i < FILES.length; i += MAX_DEXES_PER_CMD) {
  const chunk = FILES.slice(i, i + MAX_DEXES_PER_CMD);
  cp.execFileSync(
    CLI_EXEC,
    [
      "record-dex",
      ...chunk.map(
        (fName) => `${DEST_DIR}/${fName}`
      )
    ],
  )
  console.log("recorded", JSON.stringify(chunk));
}
